##
## Makefile for makefile in /home/guerga_a/rendu/Piscine_C_J13/cat
## 
## Made by francois guergadic
## Login   <guerga_a@epitech.net>
## 
## Started on  Thu Oct 23 10:19:50 2014 francois guergadic
## Last update Thu Oct 23 10:30:33 2014 francois guergadic
##

NAME	= cat

all: $(NAME)

$(NAME):
	gcc -o $(NAME) cat.c -lmy -L../lib/

clean:
	rm -r -rf cat.o main.o

fclean:
	rm -r -rf cat
